source: src
paths:
  data: _data
  collections: ''
  layouts: _layouts
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  posts:
    path: posts
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: pages
    output: true
    url:
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas: {}
    schema_key:
_enabled_editors:
  - content
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Europe/Rome
